<a href="https://colab.research.google.com/github/Jeusdhas/Data-science/blob/master/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import torch

In [22]:
import jovian

In [23]:
arr = [[3, 4], [8, 5]]   
pytensor = torch.Tensor(arr)  
print(pytensor)

tensor([[3., 4.],
        [8., 5.]])


In [24]:
from torch.utils.data import TensorDataset

In [25]:
import torch.nn as nn
import numpy as np

In [26]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [27]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [28]:
from torch.utils.data import DataLoader

In [29]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [30]:
for xb, yb in train_dl:
    print('batch:') # all batches
    print(xb)
    print(yb)
    #break

batch:
tensor([[ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.]])
tensor([[ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [ 81., 101.],
        [ 56.,  70.]])
batch:
tensor([[102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.]])
tensor([[ 22.,  37.],
        [119., 133.],
        [103., 119.],
        [ 56.,  70.],
        [ 22.,  37.]])
batch:
tensor([[ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 69.,  96.,  70.]])
tensor([[ 81., 101.],
        [119., 133.],
        [ 56.,  70.],
        [103., 119.],
        [103., 119.]])


In [49]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0900,  0.5499,  0.4440],
        [-0.0080, -0.1727,  0.1128]], requires_grad=True)
Parameter containing:
tensor([0.2373, 0.1133], requires_grad=True)


In [50]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.0900,  0.5499,  0.4440],
         [-0.0080, -0.1727,  0.1128]], requires_grad=True),
 Parameter containing:
 tensor([0.2373, 0.1133], requires_grad=True)]

In [51]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 49.6047,  -7.1893],
        [ 68.8570,  -8.5908],
        [ 91.8473, -17.1807],
        [ 31.1349,  -3.9519],
        [ 77.8990,  -9.1205],
        [ 49.6047,  -7.1893],
        [ 68.8570,  -8.5908],
        [ 91.8473, -17.1807],
        [ 31.1349,  -3.9519],
        [ 77.8990,  -9.1205],
        [ 49.6047,  -7.1893],
        [ 68.8570,  -8.5908],
        [ 91.8473, -17.1807],
        [ 31.1349,  -3.9519],
        [ 77.8990,  -9.1205]], grad_fn=<AddmmBackward>)

#LOSS FUNCTION

In [54]:
import torch.nn.functional as F

In [55]:
loss_fn = F.mse_loss

In [56]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(6025.3652, grad_fn=<MseLossBackward>)


# Optimizer

In [57]:
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

Train the **Model** 

In [58]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [59]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 415.0278
Epoch [20/100], Loss: 51.7204
Epoch [30/100], Loss: 67.9683
Epoch [40/100], Loss: 35.8865
Epoch [50/100], Loss: 34.6937
Epoch [60/100], Loss: 14.0815
Epoch [70/100], Loss: 7.8773
Epoch [80/100], Loss: 5.6542
Epoch [90/100], Loss: 4.0714
Epoch [100/100], Loss: 2.9394
